### ISSUE TITLE
Impl PartialEq and Debug for UnitTrait and UnitFormat

### ISSUE THREAD

**Issue by WCarrollSTO** [Psychoticpotato/dims#2]
This would allow checking on structs/enums that contain them, as well as making writing assertion tests much easier.

**Comment by WilliamTCarroll** [comment]
I see the `PartialEq` looking at just the `in_base` and `offset` values, so if someone were to compare `metre` with `meter`, it would be equal.

As for the debugging, what would we want to show?  All fields?  Just `in_base` and `offset` (if on formatted one)?

**Comment by WilliamTCarroll** [comment]
#3 has been merged; this is now implemented.
